server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/JSON_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      format_sql: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  flyway:
    enabled: true
    baseline-on-migrate: true
